// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using gamehub_API.DbContext;

#nullable disable

namespace gamehub_API.Migrations
{
    [DbContext(typeof(LocalDbContext))]
    [Migration("20250423184357_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("gamehub_API.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isVerified")
                        .HasColumnType("bit");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("gamehub_API.Models.Videogame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("platform")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("releaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Videogames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            genre = "Action-adventure",
                            image = "https://zelda.nintendo.com/breath-of-the-wild/assets/media/wallpapers/tablet-1.jpg",
                            platform = "Nintendo Switch",
                            publisher = "Nintendo",
                            rating = 10,
                            releaseDate = new DateTime(2017, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = "Released",
                            title = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 2,
                            genre = "Action-adventure",
                            image = "https://www.ultimagame.es/god-war-4/imagen-i19055-pge.jpg",
                            platform = "PlayStation 4",
                            publisher = "Sony Interactive Entertainment",
                            rating = 10,
                            releaseDate = new DateTime(2018, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = "Released",
                            title = "God of War"
                        },
                        new
                        {
                            Id = 3,
                            genre = "Action-adventure",
                            image = "https://i.blogs.es/juegos/13424/red_dead_3__nombre_temporal_/fotos/maestras/red_dead_3__nombre_temporal_-4030936.jpg",
                            platform = "PlayStation 4, Xbox One, PC",
                            publisher = "Rockstar Games",
                            rating = 10,
                            releaseDate = new DateTime(2018, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = "Released",
                            title = "Red Dead Redemption 2"
                        },
                        new
                        {
                            Id = 4,
                            genre = "Action RPG",
                            image = "https://cdn1.epicgames.com/offer/14ee004dadc142faaaece5a6270fb628/EGS_TheWitcher3WildHuntCompleteEdition_CDPROJEKTRED_S2_1200x1600-53a8fb2c0201cd8aea410f2a049aba3f",
                            platform = "PlayStation 4, Xbox One, PC, Nintendo Switch",
                            publisher = "CD Projekt",
                            rating = 10,
                            releaseDate = new DateTime(2015, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = "Released",
                            title = "The Witcher 3: Wild Hunt"
                        },
                        new
                        {
                            Id = 5,
                            genre = "Action RPG",
                            image = "https://muropaketti.com/wp-content/uploads/2020/12/cyberpunk-box.jpg",
                            platform = "PlayStation 4, Xbox One, PC, Stadia",
                            publisher = "CD Projekt",
                            rating = 10,
                            releaseDate = new DateTime(2020, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = "Released",
                            title = "Cyberpunk 2077"
                        },
                        new
                        {
                            Id = 6,
                            genre = "Sandbox, Survival",
                            image = "https://p2.trrsf.com/image/fget/cf/1200/1600/middle/images.terra.com/2020/09/30/minecraft-cover-art.jpg",
                            platform = "Multiple platforms",
                            publisher = "Mojang Studios",
                            rating = 10,
                            releaseDate = new DateTime(2011, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = "Released",
                            title = "Minecraft"
                        },
                        new
                        {
                            Id = 7,
                            genre = "Battle Royale, Survival",
                            image = "https://cdn1.epicgames.com/offer/fn/FNBR_34-00_C6S2_EGS_Launcher_KeyArt_FNlogo_Blade_1200x1600_1200x1600-0aa5c6ea35dab419ec28980fdb402e89",
                            platform = "Multiple platforms",
                            publisher = "Epic Games",
                            rating = 10,
                            releaseDate = new DateTime(2017, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = "Released",
                            title = "Fortnite"
                        },
                        new
                        {
                            Id = 8,
                            genre = "Battle Royale",
                            image = "https://static.serlogal.com/imagenes_big/9788467/978846795073.JPG",
                            platform = "PlayStation 4, Xbox One, PC, Nintendo Switch",
                            publisher = "Electronic Arts",
                            rating = 10,
                            releaseDate = new DateTime(2019, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = "Released",
                            title = "Apex Legends"
                        },
                        new
                        {
                            Id = 9,
                            genre = "Party, Social Deduction",
                            image = "https://example.com/amongus.jpg",
                            platform = "PC, Mobile, Nintendo Switch",
                            publisher = "Innersloth",
                            rating = 10,
                            releaseDate = new DateTime(2018, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = "Released",
                            title = "Among Us"
                        },
                        new
                        {
                            Id = 10,
                            genre = "Roguelike, Action RPG",
                            image = "https://example.com/hades.jpg",
                            platform = "PC, Nintendo Switch",
                            publisher = "Supergiant Games",
                            rating = 10,
                            releaseDate = new DateTime(2020, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = "Released",
                            title = "Hades"
                        },
                        new
                        {
                            Id = 11,
                            genre = "Action-adventure",
                            image = "https://example.com/lastofus2.jpg",
                            platform = "PlayStation 4",
                            publisher = "Sony Interactive Entertainment",
                            rating = 10,
                            releaseDate = new DateTime(2020, 6, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = "Released",
                            title = "The Last of Us Part II"
                        },
                        new
                        {
                            Id = 12,
                            genre = "Action-adventure",
                            image = "https://example.com/ghostoftsushima.jpg",
                            platform = "PlayStation 4",
                            publisher = "Sony Interactive Entertainment",
                            rating = 10,
                            releaseDate = new DateTime(2020, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = "Released",
                            title = "Ghost of Tsushima"
                        },
                        new
                        {
                            Id = 13,
                            genre = "Action RPG",
                            image = "https://example.com/horizonzerodawn.jpg",
                            platform = "PlayStation 4, PC",
                            publisher = "Sony Interactive Entertainment",
                            rating = 10,
                            releaseDate = new DateTime(2017, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = "Released",
                            title = "Horizon Zero Dawn"
                        },
                        new
                        {
                            Id = 14,
                            genre = "Action-adventure",
                            image = "https://example.com/sekiro.jpg",
                            platform = "PlayStation 4, Xbox One, PC",
                            publisher = "Activision",
                            rating = 10,
                            releaseDate = new DateTime(2019, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = "Released",
                            title = "Sekiro: Shadows Die Twice"
                        },
                        new
                        {
                            Id = 15,
                            genre = "Survival horror",
                            image = "https://example.com/residentevilvillage.jpg",
                            platform = "PlayStation 4, PlayStation 5, Xbox One, Xbox Series X/S, PC",
                            publisher = "Capcom",
                            rating = 10,
                            releaseDate = new DateTime(2021, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = "Released",
                            title = "Resident Evil Village"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
